# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [3]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [6]:
x = np.arange(10, 50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [8]:
x.shape

(40,)

5. Print the type of the previous array in question 3

In [11]:
print(type(x))

<class 'numpy.ndarray'>


6. Print the numpy version and the configuration


In [13]:
print(np.__version__)
print(np.show_config())

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/syed.jamil/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/syed.jamil/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/syed.jamil/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117

7. Print the dimension of the array in question 3


In [15]:
print(x.ndim)

1


8. Create a boolean array with all the True values

In [18]:
bool_arr = np.ones(10, dtype=bool)
bool_arr

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

9. Create a two dimensional array




In [23]:
arr_2d = np.array([[1,1],[2,2]])
arr_2d

array([[1, 1],
       [2, 2]])

10. Create a three dimensional array



In [24]:
arr_3d = np.array([[1,1], [2,2], [3,3]])
arr_3d

array([[1, 1],
       [2, 2],
       [3, 3]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [27]:
rev_vec = np.array([1,2,3,4])
np.flip(rev_vec)

array([4, 3, 2, 1])

12. Create a null vector of size 10 but the fifth value which is 1 

In [28]:
null_vec = np.zeros(10)
null_vec[4] = 1
null_vec

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [30]:
identity_mat = np.identity(3)
identity_mat

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [35]:
arr = np.array([1, 2, 3, 4, 5])
arr = arr.astype('float')
arr

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [39]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

np.multiply(arr1, arr2)

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [40]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

arr_comparison = arr1 == arr2
arr_comparison

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [46]:
arr = np.arange(0,10)
odd_nums = arr[arr%2 == 1]
odd_nums

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [49]:
arr[arr%2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [56]:
arr = np.arange(10)
arr[[5, 6, 7, 8]] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [57]:
arr_2d = np.ones((10,10))
arr_2d[1:-1,1:-1] = 0
arr_2d

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [60]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[arr2d == 5] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [65]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0][0] = 64
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [71]:
arr_2d = np.arange(0,10).reshape(2,5)
arr_2d = arr_2d[1:]
arr_2d

array([[5, 6, 7, 8, 9]])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [93]:
arr_2d = np.arange(0,10).reshape(2,5)
np.delete(arr_2d[1], 1)

array([5, 7, 8, 9])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [86]:
arr_2d = np.arange(0,10).reshape(2,5)
arr_2d[:,[0,1,2,4]]

array([[0, 1, 2, 4],
       [5, 6, 7, 9]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [97]:
arr_10d = np.random.random((10,10))
arr_min, arr_max = arr_10d.min(), arr_10d.max()

print(arr_min, arr_max)

0.00524707509639355 0.9939499905615032


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [99]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [104]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a==b)[0]

array([1, 3, 5, 7], dtype=int64)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [109]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)

data[np.where(names!= 'Will')]


array([[ 2.2741815 ,  0.5423728 ,  0.29765124, -0.24505761],
       [ 1.0803526 , -1.00967698,  1.2301429 , -0.29382438],
       [-2.12019088, -0.00690316,  1.54815602, -0.39754172],
       [-0.79028522, -0.07531367,  0.67752437, -0.78473603],
       [-1.14846658, -0.34640322, -0.00334508,  0.69502086]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [126]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)

data[np.where((names!= 'Will') & (names!='Joe'))]

array([[-0.25685418,  1.262587  , -0.2383621 , -0.52574687],
       [ 2.24676451, -0.26665363, -0.68280746, -2.02188358]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [149]:
arr_2d = np.arange(1,16).reshape(5,3).astype('float')
arr_2d

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.],
       [13., 14., 15.]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [150]:
arr_2d = np.arange(1,17).reshape(2,2,4).astype('float')
arr_2d

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[ 9., 10., 11., 12.],
        [13., 14., 15., 16.]]])

33. Swap axes of the array you created in Question 32

In [152]:
np.swapaxes(arr_2d,0,1)

array([[[ 1.,  2.,  3.,  4.],
        [ 9., 10., 11., 12.]],

       [[ 5.,  6.,  7.,  8.],
        [13., 14., 15., 16.]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [163]:
arr = np.arange(1,11)

arr = np.sqrt(arr)

arr[arr < 0.5] = 0
arr

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [175]:
arr1 = np.random.randint(12, size= 10)
arr2 = np.random.randint(12, size= 10)

print('Array 1 : ', arr1)
print('Array 2 : ', arr2)

max_arr = np.maximum(arr1, arr2)
max_arr

Array 1 :  [ 7  7 11 11  1  9  1  7  9  1]
Array 2 :  [5 9 5 0 0 2 7 9 4 4]


array([ 7,  9, 11, 11,  1,  9,  7,  9,  9,  4])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [179]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.sort(np.unique(names))

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [185]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])

a = np.setdiff1d(a, b)
a

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [189]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])

sampleArray = np.delete(sampleArray, 1, axis=1) # delete second column

np.insert(sampleArray, 1, newColumn, axis=1) # insert new column in its place

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [190]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])

np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [196]:
rand_mat = np.random.randint(100, size= (4,5))

print(rand_mat)

print('\nCumulative sum :', np.cumsum(rand_mat))


[[66 77 72 33 35]
 [99 77 42 73 24]
 [35 42 94 51 59]
 [36 86  5  8  6]]

Cumulative sum : [  66  143  215  248  283  382  459  501  574  598  633  675  769  820
  879  915 1001 1006 1014 1020]
