# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [4]:
import numpy as np

arr = np.arange(0,10)
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [16]:
arr1 = np.arange(0,10).reshape(2,5).astype('int')
arr2 = np.ones(10).reshape(2,5).astype('int')
np.concatenate((arr1, arr2), axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [17]:
arr1 = np.arange(0,10).reshape(2,5).astype('int')
arr2 = np.ones(10).reshape(2,5).astype('int')
np.concatenate((arr1, arr2), axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [21]:
arr = np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
arr.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [22]:
arr = np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9], [10, 11, 12, 13, 14]])
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [24]:
arr = np.array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
arr.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [31]:
arr = np.random.randint(100, size= (5,5))
np.square(arr)

array([[2809, 2401,    4,  484, 4356],
       [ 144,  289,  576,  576,  529],
       [ 144, 3721,    4, 8836,   25],
       [ 676, 3969, 8836, 7569, 8836],
       [1600, 4489,  484, 2601, 5776]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [41]:
arr = np.random.randint(100, size= (5,6))
print(arr)

print('Mean : ', np.mean(arr))

[[66 27 39 17 40 63]
 [64 48 63 95 43 84]
 [99 49 39 79 26 91]
 [60 31 49 69 76 38]
 [37 25 56  2  0 90]]
Mean :  52.166666666666664


## Question:9

### Find the standard deviation of the previous array in Q8?

In [42]:
np.std(arr)

25.961616967276047

## Question:10

### Find the median of the previous array in Q8?

In [43]:
np.median(arr)

49.0

## Question:11

### Find the transpose of the previous array in Q8?

In [44]:
np.transpose(arr)

array([[66, 64, 99, 60, 37],
       [27, 48, 49, 31, 25],
       [39, 63, 39, 49, 56],
       [17, 95, 79, 69,  2],
       [40, 43, 26, 76,  0],
       [63, 84, 91, 38, 90]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [46]:
arr = np.random.randint(100, size= (4,4))
print(arr)

print('Sum of diagonal elements is : ', np.trace(arr))

[[99 19 93 67]
 [76 28 33 33]
 [26 51 22 57]
 [33 13 91 41]]
Sum of diagonal elements is :  190


## Question:13

### Find the determinant of the previous array in Q12?

In [48]:
np.linalg.det(arr)

-6001399.999999991

## Question:14

### Find the 5th and 95th percentile of an array?

In [49]:
arr = np.array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
np.percentile(arr,[5, 95])

array([ 0.7, 13.3])

## Question:15

### How to find if a given array has any null values?

In [59]:
arr = np.array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

np.isnan(arr).any()

False